Enable integration tests in nightly

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -6,54 +6,121 @@ on:
     - cron: "30 01 * * *"
 
 jobs:
-  prepare-files:
+  integration-tests:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 21
-      uses: actions/setup-java@v4
-      with:
-        java-version: 21
-        distribution: temurin
-        cache: maven
-    - name: Build with Maven
-      run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
-    - name: Create new prescriptions in FMK
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
-    - name: Get the prescriptions from FMK
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
-    - name: Generate ePrescription documents
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
-    - name: Upload test files as artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-files
-        path: testing-shared/src/main/resources/test-file-storage
-
-  edispensation-generation:
-    runs-on: ubuntu-latest
-    needs: prepare-files
-    steps:
-      - name: Download test files
-        uses: actions/download-artifact@v4
+      - uses: actions/checkout@v4
         with:
-          name: test-files
-          path: input-files
+          fetch-depth: 5 # for commit history
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: 21
+          distribution: temurin
+          cache: maven
+      - name: Build with Maven
+        run:  |
+          cd country-a-service
+          mvn --batch-mode --projects testing-tools --also-make -DskipUTs package
+      - name: Create a new prescription in FMK
+        run: |
+          java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar \
+          dk.nsp.epps.script.FmkPrescriptionCreator \
+          0201909309
+      - name: Get the prescription from FMK
+        run: |
+          java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar \
+          dk.nsp.epps.script.FmkPrescriptionCollector \
+          0201909309 \
+          target/test-files/get-prescription.xml
+      - name: Generate ePrescription document
+        run: |
+          java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar \
+          dk.nsp.epps.script.ePrescriptionCdaGenerator \
+          target/test-files/get-prescription.xml \
+          target/test-files/eprescription-cda.xml
+
       - name: Set up Docker
         run: sudo service docker start
 
       - name: Log in to GitHub Container Registry
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
+      # ehealth-portal-edispensation-generator is built at https://github.com/Sundhedsdatastyrelsen/ehealth-portal
       - name: Generate eDispensation CDA
         run: |
           docker pull ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli
           docker run \
-          -v ${{ github.workspace }}/input-files/cda-prepared-0201909309.xml:/opt/app/input/ep.xml \
-          ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > input-files/edispensation-cda.xml
+          -v ${{ github.workspace }}/target/test-files/eprescription-cda.xml:/opt/app/input/ep.xml \
+          ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > target/test-files/edispensation-cda.xml
 
-      - name: Upload eDispensation CDAs as artifact
+      - name: Log out of GitHub Container Registry
+        if: success() || failure() # always run even if the previous step fails
+        run: docker logout ghcr.io
+
+      - name: Upload test files
         uses: actions/upload-artifact@v4
         with:
-          name: output-files
-          path: input-files
+          name: ep-and-ed-files
+          path: target/test-files/
+
+      - name: Run integration tests
+        run: |
+          cd country-a-service
+          mvn --batch-mode --projects integration-tests --also-make \
+            verify -DskipITs=false -DskipUTs \
+            -DeDispensationITPath=${{ github.workspace }}/target/test-files/edispensation-cda.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'country-a-service/integration-tests/target/failsafe-reports/TEST-*.xml'
+          check_name: Integration Test Report
+
+      - name: Prepare commit history
+        if: failure() # only post on slack if tests fail
+        # The "jq" command escapes the strings for json transport
+        run: |
+          COMMIT_LOG=$(git log -5 \
+            --pretty=format:'<https://github.com/${{ github.repository }}/commit/%h|%h> - %s (%an)')
+          echo "COMMIT_LOG=$(jq -Rn --arg str "$COMMIT_LOG" '$str')" >> $GITHUB_ENV
+
+          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
+
+      - name: Post to a Slack channel
+        id: slack
+        uses: slackapi/slack-github-action@v1.27.0
+        if: failure() # only post on slack if tests fail
+        # See: https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-2-slack-app
+        with:
+          # channel-id: 'C07Q2AG46HL' # #github-actions-bot-test
+          channel-id: 'C079YA9DB61' # #github-notifications
+          payload: |
+            {
+              "attachments": [
+                {
+                  "fallback": "Test Results Report - ${{ github.repository }}",
+                  "color": "danger",
+                  "title": ":warning: Integration Test Failure Alert",
+                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+                  "text": "Nightly integration test run in *${{ github.repository }}* failed. Check the <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Actions details>.",
+                  "fields": [
+                    {
+                      "title": "Branch",
+                      "value": "${{ github.ref_name }}",
+                      "short": true
+                    },
+                    {
+                      "title": "Recent Commits",
+                      "value": ${{ env.COMMIT_LOG }}
+                    }
+                  ],
+                  "footer": "GitHub Actions",
+                  "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
+                  "ts": ${{ env.TIMESTAMP }}
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
