try with single job

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -6,91 +6,63 @@ on:
     - cron: "30 01 * * *"
 
 jobs:
-  prepare-files:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 21
-      uses: actions/setup-java@v4
-      with:
-        java-version: 21
-        distribution: temurin
-        cache: maven
-    - name: Build with Maven
-      run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
-    - name: Create new prescriptions in FMK
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
-    - name: Get the prescriptions from FMK
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
-    - name: Generate ePrescription documents
-      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
-    - name: Upload test files as artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-files
-        path: testing-shared/src/main/resources/test-file-storage
-
-  edispensation-generation:
-    runs-on: ubuntu-latest
-    needs: prepare-files
-    steps:
-      - name: Download test files
-        uses: actions/download-artifact@v4
-        with:
-          name: test-files
-          path: input-files
-      - name: Set up Docker
-        run: sudo service docker start
-
-      - name: Log in to GitHub Container Registry
-        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-
-      - name: Generate eDispensation CDA
-        run: |
-          docker pull ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli
-          docker run \
-          -v ${{ github.workspace }}/input-files/cda-prepared-0201909309.xml:/opt/app/input/ep.xml \
-          ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > input-files/edispensation-cda.xml
-
-      - name: Upload eDispensation CDAs as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ep-and-ed-files
-          path: input-files
-
   integration-tests:
     runs-on: ubuntu-latest
-    needs: edispensation-generation
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Download input files
-        uses: actions/download-artifact@v4
-        with:
-          name: ep-and-ed-files
-          path: input-files
-
+      - uses: actions/checkout@v4
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
           java-version: 21
           distribution: temurin
           cache: maven
+      - name: Build with Maven
+        run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
+      - name: Create new prescriptions in FMK
+        run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
+      - name: Get the prescriptions from FMK
+        run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
+      - name: Generate ePrescription documents
+        run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
+      - name: Set up Docker
+        run: sudo service docker start
+
+      - name: Log in to GitHub Container Registry
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+        # TODO: fix path
+      - name: Generate eDispensation CDA
+        run: |
+          docker pull ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli
+          docker run \
+          -v ${{ github.workspace }}/testing-shared/src/main/resources/test-file-storage/cda-prepared-0201909309.xml:/opt/app/input/ep.xml \
+          ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > testing-shared/src/main/resources/test-file-storage/edispensation-cda.xml
+      - name: Upload eDispensation CDAs as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ep-and-ed-files
+          path: testing-shared/src/main/resources/test-file-storage/
 
       - name: Run integration tests
         run: |
           cd country-a-service
           mvn --batch-mode --projects integration-tests --also-make \
             verify -DskipITs=false -DskipUTs \
-            -DeDispensationITPath=input-files/edispensation-cda.xml
+            -DeDispensationITPath=${{ github.workspace }}/testing-shared/src/main/resources/test-file-storage/edispensation-cda.xml
 
-      - name: Upload Failsafe test reports (for debugging purposes)
-        uses: actions/upload-artifact@v4
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
-          name: failsafe-reports
-          path: country-a-service/integration-tests/target/failsafe-reports
+          report_paths: 'country-a-service/integration-tests/target/failsafe-reports/TEST-*.xml'
+
+
+      # - name: Upload Failsafe test reports (for debugging purposes)
+      #   uses: actions/upload-artifact@v4
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     name: failsafe-reports
+      #     path: country-a-service/integration-tests/target/failsafe-reports
 
       - name: Post to a Slack channel
         id: slack
@@ -107,3 +79,108 @@ jobs:
             ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+
+
+
+
+  # prepare-files:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up JDK 21
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: 21
+  #       distribution: temurin
+  #       cache: maven
+  #   - name: Build with Maven
+  #     run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
+  #   - name: Create new prescriptions in FMK
+  #     run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
+  #   - name: Get the prescriptions from FMK
+  #     run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
+  #   - name: Generate ePrescription documents
+  #     run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
+  #   - name: Upload test files as artifact
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: test-files
+  #       path: testing-shared/src/main/resources/test-file-storage
+
+  # edispensation-generation:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare-files
+  #   steps:
+  #     - name: Download test files
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: test-files
+  #         path: input-files
+  #     - name: Set up Docker
+  #       run: sudo service docker start
+
+  #     - name: Log in to GitHub Container Registry
+  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+  #     - name: Generate eDispensation CDA
+  #       run: |
+  #         docker pull ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli
+  #         docker run \
+  #         -v ${{ github.workspace }}/input-files/cda-prepared-0201909309.xml:/opt/app/input/ep.xml \
+  #         ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > input-files/edispensation-cda.xml
+
+  #     - name: Upload eDispensation CDAs as artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ep-and-ed-files
+  #         path: input-files
+
+  # integration-tests:
+  #   runs-on: ubuntu-latest
+  #   needs: edispensation-generation
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v2
+
+  #     - name: Download input files
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: ep-and-ed-files
+  #         path: input-files
+
+  #     - name: Set up JDK 21
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: 21
+  #         distribution: temurin
+  #         cache: maven
+
+  #     - name: Run integration tests
+  #       run: |
+  #         cd country-a-service
+  #         mvn --batch-mode --projects integration-tests --also-make \
+  #           verify -DskipITs=false -DskipUTs \
+  #           -DeDispensationITPath=input-files/edispensation-cda.xml
+
+  #     - name: Upload Failsafe test reports (for debugging purposes)
+  #       uses: actions/upload-artifact@v4
+  #       if: success() || failure() # always run even if the previous step fails
+  #       with:
+  #         name: failsafe-reports
+  #         path: country-a-service/integration-tests/target/failsafe-reports
+
+  #     - name: Post to a Slack channel
+  #       id: slack
+  #       uses: slackapi/slack-github-action@v1.27.0
+  #       if: success() || failure() # always run even if the previous step fails
+  #       with:
+  #         # Slack channel id, channel name, or user id to post message.
+  #         # See also: https://api.slack.com/methods/chat.postMessage#channels
+  #         # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
+  #         channel-id: 'C07Q2AG46HL' # #github-actions-bot-test
+  #         # For posting a simple plain text message
+  #         slack-message: |
+  #           GitHub build result: ${{ job.status }}
+  #           ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
+  #       env:
+  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
